services:
  user-service:
    build: ./user_service
    ports:
      - "8001:8000"
    networks:
      - backend

  order-service:
    build: ./order_service
    ports:
      - "8002:8000"
    networks:
      - backend
    depends_on:
      - user-service

  nginx:
    image: nginx:stable
    ports:
      - "8080:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - user-service
      - order-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
